### ISSUE TITLE
async dependency

### ISSUE THREAD

**Issue by runelabs** [gmp26/grunt-panda#1]
Hi,
it seems the async module is not included as a dependency for this plugin.
This means the user has to have the async module installed globally before being able to use the plugin.
Adding a section in the `package.json` file fixes this:

```
  "dependencies": {
    "async": "~0.2.9"
  },
```

For now it is only listed in the devDependencies section ;-)

Cheers!

**Comment by gmp26** [comment]
Thankyou!

Be aware of #2 too.

**Comment by gmp26** [comment]
Fixed in 8315361edada3bbddb0fee8d944b875c666dd4a7
